### ISSUE TITLE
Updating MOTD

### ISSUE THREAD

**Issue by amlamarra** [rooty0/freebsd-dynamic-motd#1]
How is this script run? How do you actually get the /etc/motd file updated each time someone SSH's to the FreeBSD machine?

**Comment by rooty0** [comment]
I use ZSH shell, for me it's 
```bash
# cat $HOME/.zprofile
echo ""
echo ""
sudo /usr/home/stan/apps/freebsd-dynamic-motd/motd.sh
echo ""
```
If you use bash, you need to modify your `$HOME/.profile` instead

**Comment by amlamarra** [comment]
Ahh, I see. Thanks!
